- hosts: all
  become: true
  tasks:
   - name: gather current kernel version
     shell: "needrestart -b | sed -n -e 's/^.*NEEDRESTART-KCUR: //p'"
     register: current_kernel_version
   - name: gather expected kernel version
     shell: "needrestart -b | sed -n -e 's/^.*NEEDRESTART-KEXP: //p'"
     register: expected_kernel_version
   - name: gather whether any services need to be restarted
     shell: "needrestart -b | sed -n -e 's/^NEEDRESTART-SVC: //p'"
     register: outdated_services
   - debug:
       msg: Rebooting system {{ inventory_hostname }} (IP {{ ansible_default_ipv4.address }})
     when: current_kernel_version.stdout != expected_kernel_version.stdout or outdated_services.stdout != ""
   - name: Reboot server
     reboot:
       msg: "Ansible initiated reboot to apply updates"
       connect_timeout: 5
       reboot_timeout: 300
       pre_reboot_delay: 0
       post_reboot_delay: 20
     when: current_kernel_version.stdout != expected_kernel_version.stdout or outdated_services.stdout != ""
