- hosts: virtual_machines
  become: true
  tasks:
   - name: Edit SSH configuration
     template:
       src: templates/sshd_config.j2
       dest: /etc/ssh/sshd_config
       mode: 0644
     register: ssh_config
   - name: Restart SSH if necessary
     service:
       name: sshd
       state: restarted
     when: ssh_config.changed
