- hosts: all
  become: true
  tasks:
   - name: update and upgrade server
     apt:
       cache_valid_time: 3600
       update_cache: yes
       upgrade: 'yes'
   - name: autoremove packages
     apt:
       autoremove: yes
